[project]
name = "Quantitative-Portfolio-Backtester"
package-mode = false
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "JoshuaKoeck", email = "joshua.koeck@stud.tu-darmstadt.de"},
]
dependencies = [
    "streamlit",
    "yfinance",
    "watchdog",
    "pandas",
    "plotly",
]

requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = { cmd = "streamlit run web/main.py --server.port $PORT --server.address 0.0.0.0", env = { PYTHONPATH = "." } }
dev = { cmd = "streamlit run web/main.py", env = { PYTHONPATH = "." } }